name: Code Quality Check

on:
  push:
    branches:
      - develop

jobs:
  lint:
    name: Run Flake8 and Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8
        id: flake8
        run: |
          flake8 zfskeyprovider/main.py > flake8_output.txt || true
          if [ -s flake8_output.txt ]; then
            echo "issues=true" >> $GITHUB_OUTPUT
          else
            echo "issues=false" >> $GITHUB_OUTPUT
          fi

      - name: Update README badge
        run: |
          if [ "${{ steps.flake8.outputs.issues }}" = "true" ]; then
            sed -i 's|!\[Lint Status\](.*)|![Lint Status](https://img.shields.io/badge/lint-warning-yellow)|' README.md
          else
            sed -i 's|!\[Lint Status\](.*)|![Lint Status](https://img.shields.io/badge/lint-passing-brightgreen)|' README.md
          fi

      - name: Commit badge update
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md
          git commit -m "Update lint badge" || echo "No changes"
          git push
